01 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'SÉRIE';

02 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'SÉRIE' ORDER BY NOME ASC;

03 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'SÉRIE' ORDER BY NOME DESC;

04 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'FILME';

05 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'FILME' AND ANO_LANCAMENTO < 2000;

06 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'SÉRIE' AND ANO_LANCAMENTO > 2015;

07 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'FILME' AND GENERO LIKE '%Ação%';

08 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'FILME' AND DURACAO_MINUTOS > 120;

09 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'SÉRIE' AND ANO_LANCAMENTO BETWEEN 2012 AND 2016 ORDER BY ANO_LANCAMENTO ASC, NOME ASC;

10 SELECT * FROM ENTRETERIMENTO WHERE TIPO = 'FILME' AND ATOR_PRINCIPAL = 'Brad Pitt' ORDER BY ANO_LANCAMENTO ASC;

11 SELECT NOME, DIRETOR, ATOR_PRINCIPAL FROM ENTRETERIMENTO WHERE GENERO LIKE '%Crime%' AND ATOR_PRINCIPAL = 'John Travolta';

12 SELECT * FROM ENTRETERIMENTO WHERE DURACAO_MINUTOS > 120 AND (ATOR_PRINCIPAL NOT IN ('Christian Bale', 'Tim Robbins') OR ATOR_PRINCIPAL IS NULL);

13 SELECT * FROM ENTRETERIMENTO WHERE GENERO NOT LIKE '%Comédia%' AND GENERO NOT LIKE '%Drama%';

14 SELECT * FROM ENTRETERIMENTO WHERE ANO_LANCAMENTO NOT IN (2000, 2001, 2002);

15 SELECT * FROM ENTRETERIMENTO WHERE ATOR_PRINCIPAL IN ('Wagner Moura', 'Leonardo DiCaprio', 'Keanu Reeves');
